version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: pub
    directory: "/packages/jxl"
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: "/packages/jxl/example"
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: "/packages/flutter_jxl"
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: "/packages/flutter_jxl/example"
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: "/packages/jxl/native"
    schedule:
      interval: weekly