[package]
name = "jxl"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = "1.82.4"

[dependencies]
flutter_rust_bridge = "1.82.4"
jxl-oxide = "0.7.0"
lazy_static = "1.4.0"
